### ISSUE TITLE
Save docFreq and params inside the DB

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#112]
Propose a DB schema for saving docFreq and params inside DB, instead of .json in FS.

Then migrate:
   * hash, to writing to DB 
   * query, to reading params from DB

**Comment by bzz** [comment]
One thing I'd like to understand better is: given the same vocabulary (and thus re-using a docFreq) it is reasonable to expect a user to re-run `./hash` multiple times with different similarity threshold settings, thus, generating new params. And then later using one of those for `./report` or `./query`.

Would this use-case change anything in DB vs Files scenario? Pointing to a separate files through CLI is very intuitive.

At the same time, hash would produce a different DBs with hashes on every run, so if we do accommodate such use-case only by switching a full `--keyspaces` now - it does not matter that much.

**Comment by smacker** [comment]
It's a bad idea to use different docFreq with the same DB (with multiple re-run of hash). It might start to produce wrong results because the same files will have multiple hashes in DB (for each new docFreq). Then query and report would use hashes from old runs too. (not sure how real collisions are in real life, but still).
Switching namespaces is better choice for such case.

**Comment by bzz** [comment]
Agreed.

This would also allow us to get rid of using [scala.util.parsing.json](https://github.com/scala/scala-parser-combinators/blob/8e8e88042c20a327464c71b1376de72c72ec0bd7/shared/src/main/scala/scala/util/parsing/json/package.scala#L4) which sounds very good due to:
   
>  This package was never intended for production use; it's really more of a code sample demonstrating how to use parser combinators.

**Comment by smacker** [comment]
Schema:

```
CREATE TABLE docfreq (
    id text PRIMARY KEY,
    docs int,
    df map<text, int>
);
```

map is a sorted type already according to the docs: http://docs.scylladb.com/getting-started/types/#maps

for now, we can hard-code `id` but it can be useful to be able to save more than 1 docfreq in the future.
