### ISSUE TITLE
File-similarity: apply default parameters, found by ML team

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#113]
ML team [has done extensive research](https://github.com/src-d/backlog/issues/1197#issuecomment-383632529) on number of optimal parameters for file-based similarity detection:
 - best feature extractors for this job
 - feature extractors weights
 - threshold
 - hash size

@EgorBu could you please take a look and help by:
 - check that no parameters are missing from the list above
 - provide a default values for those, that we should be using in Gemini

**Comment by EgorBu** [comment]
parameters for val_acc 0.9497 - best so far
* best combination of feature extractors`('lit', 'id', 'graphlet')`
* `id_split_stem True` - identifiers should be splitted
* `lit_weight 264.38490183192016`
* `id_weight 194.2959667378745`
* `graphlet_weight 547.7754676767302`
* `threshold 0.6456707644812872`
* `hash size 160`
