### ISSUE TITLE
Fix warnings during hash

### ISSUE THREAD

**Issue by smacker** [src-d/gemini#114]
```
 WARN 17:34:14 org.apache.spark.internal.Logging$class (Logging.scala:66) - closing repository at /private/var/folders/qq/2hysx6wj34d040mcby284j300000gn/T/spark-e15acd68-2750-4766-ac64-5e206c2b1df3/processing-repositories/98BF14C1C68B5DA9A22379A829C945AE/9279be3cf07fb3cca4fc964b27acea57e0af461b.siva; returning object to the pool failed because it was already returned
```

reproducible locally and in CI.

Need to find out the reason and fix or silent it.

**Comment by smacker** [comment]
Fix is here: https://github.com/src-d/engine/pull/391

**Comment by smacker** [comment]
The fix is merged. We need to update engine when a new version is released.

**Comment by bzz** [comment]
Sounds great

**Comment by bzz** [comment]
Has been fixed now

**Comment by smacker** [comment]
Nope. The current version of engine is 0.6.1 and it doesn't contain the fix.

**Comment by bzz** [comment]
👍 thank you keeping issue updated

Let's close with PR updating the version as soon it's cut https://github.com/src-d/engine/pull/391#issuecomment-390131011

**Comment by bzz** [comment]
https://github.com/src-d/engine/releases/tag/v0.6.2 has just been release by source{d} awesome DR team.
