### ISSUE TITLE
Refactoring: handle all CLI in common opts parser

### ISSUE THREAD

**Issue by smacker** [src-d/gemini#120]
1. Apps parsers should inherit base parser with common options like db, versbose and so on.
2. Add support to read the same options from env variables

**Comment by bzz** [comment]
This will allow to get rid of https://github.com/src-d/gemini/blob/master/scripts/common_params.sh

**Comment by bzz** [comment]
Do not forget: change shell wrappers to remove this https://github.com/src-d/gemini/pull/125/files#r194036469

**Comment by bzz** [comment]
and also remove it from `./release.sh`
