### ISSUE TITLE
Refactoring: get list of supported languages from bblfsh

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#129]
Now, that https://github.com/bblfsh/bblfshd/releases/tag/v2.5.0 is released, let's
 - after https://github.com/bblfsh/client-scala/issues/68 is resolved
 - do https://github.com/src-d/gemini/blob/632680701f95cf9f5620dd86bf61fcca99751b0e/src/main/scala/tech/sourced/gemini/Hash.scala#L66
 - update https://github.com/src-d/gemini/blob/632680701f95cf9f5620dd86bf61fcca99751b0e/docker-compose.yml#L35
 - update README, documenting min bblfshd version compatibility

**Comment by smacker** [comment]
bblfsh/client-scala#68 was resolved https://github.com/bblfsh/client-scala/pull/69

**Comment by smacker** [comment]
Do we really need to filter it on our side?

There is a PR to engine https://github.com/src-d/engine/pull/404 which would return empty UAST to unsupported languages so they will be filtered by current
```
.filter(_.getAs[Seq[Array[Byte]]]("uast").nonEmpty)
```

**Comment by bzz** [comment]
Yup, we can skip filtering on our side now
