### ISSUE TITLE
Function-similarity: apply default parameters, found by ML team

### ISSUE THREAD

**Issue by EgorBu** [src-d/gemini#150]
Parameters for val_acc 91.6% (used for optimization) and test_acc 90.6% (hold out):
* best combination of feature extractors`('id', 'uast2seq', 'graphlet')` (it looks like that structural information even more important for functions because of lack of literals)
* `id_split_stem True` - identifiers should be splitted
* `'uast2seq_weight': 369`
* `''id_weight': 535`
* `graphlet_weight': 5707`
* `'threshold': 0.592`
* `hash size 256`
* `'uast2seq_seq_len': 3`
* `'uast2seq_stride': 1`

**Comment by bzz** [comment]
@EgorBu thanks for detailed info!

Feature extractor parameters were taken care of  https://github.com/src-d/gemini/pull/160 the rest is tracked under #162

**Comment by smacker** [comment]
fixed
