### ISSUE TITLE
Parametarise DB connection URL

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#2]
At least 
 - URL to Cassandra/ScyllaDB
 - `limit` on the number of processed repositories (only for `./hash`)

should be exposed though configuration.

CLI https://github.com/src-d/gemini#cli-arguments should be used to set Apache Spark configuration properties, as some commands do not use Spark (`./hash` or `./report`)

**Comment by bzz** [comment]
This can be done together, or separate from #12

**Comment by smacker** [comment]
Looks like it's easier to do together with #12

**Comment by bzz** [comment]
`limit` is very useful for debugging on actual cluster, if applied to the commands when data is scanned in HDFS - this way Job execution time does not depend on the cluster or the size of the data available.

URL with DB connection is a standard way of pointing to DB and is a must for every command that talks to DB.
