### ISSUE TITLE
Update output of Spark application

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#21]
For `./hash`
 migrate to [logger](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/internal/Logging.scala), provided by Apache Spark
 output: mute meaningless Spark logs (though log4j.config)
 

This would most probably mean to refactor `Gemini` class to have logging dependency injected (thorough constructor or `.set...()`), as it will be instantiated by the client (Spark/non-spark ones) in a different ways.

**Comment by smacker** [comment]
fixed
