### ISSUE TITLE
Add CI hook to push image to docker hub

### ISSUE THREAD

**Issue by smacker** [src-d/gemini#33]
Let's decide about tags/branch on which it should happen later.

The current proposal is to build images from 2 branches:
- master
- experimental

**Comment by smacker** [comment]
Let's wait for Maximo opinion about this one first: https://github.com/src-d/ci/pull/50

**Comment by dpordomingo** [comment]
I'd vote "yes"

**Comment by bzz** [comment]
Have asked Maximo to review, shall be merged any time soon!

**Comment by bzz** [comment]
src-d/ci#50 is merged now.

**Comment by smacker** [comment]
@bzz could you please add necessary environment variables in travis?

**Comment by bzz** [comment]
@smacker done

**Comment by bzz** [comment]
@smacker thank you for taking care of this - could you also please assign this issue to yourself?
