### ISSUE TITLE
Release v0.0.1

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#38]
Setup release automation if needed and produce a first release.

 - tag
 - release notes
 - GH release
 - CI automation on tag
 - push image to DockerHub (handled separately under #33 )

**Comment by smacker** [comment]
what do you want to upload to GitHub as release? 3 jars?

**Comment by bzz** [comment]
Basically, yes - an archive with jars and sh wrappers that would allow external users to try out gemini + instructions how to do that, given the release archive.

**Comment by smacker** [comment]
@bzz need to add `GITHUB_TOKEN` environment variable to travis settings.

**Comment by bzz** [comment]
@smacker done

**Comment by smacker** [comment]
@bzz do you what to use the same wrappers as we have right now?

**Comment by bzz** [comment]
Yes, I belive same files should be fine by now. 
What do you think?

**Comment by smacker** [comment]
it requires to put everything related to `sbt` in tarball. And dependencies will be downloaded on user machine. Do we want it? Or do we want to have everything in jar?

**Comment by smacker** [comment]
Agreed IRL:
- use current scripts
- put everything that is needed for sbt in tarball
- user will have to have local spark to run `hash` command
