### ISSUE TITLE
Report: connected components

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#58]
Part of the https://github.com/src-d/gemini/issues/54: update Scala implementation of the report to write a Connected Components of similar-files graph.

TODO:
 - query a DB for candidates [graph.py#find_connected_components()](https://github.com/src-d/apollo/blob/master/apollo/graph.py#L90)
 - detect [connected components](https://github.com/src-d/apollo/blob/master/apollo/graph.py#L62)
 - define Parquet schema and write the results on disk

**Comment by smacker** [comment]
Pr is merged.
