### ISSUE TITLE
Report: community detection cli app

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#60]
Part of https://github.com/src-d/gemini/issues/54: small app to read connected components, do community detection and pretty-print the results.
 
A CLI app in Python, that reads the connected components from Parquet created in #58, does community detection using the library in #59 and prints the output to STDOUT, in a format consistent \w current duplicate output format.

A call to this app should also be included in `./report`, right after a duplicate detection, so for a end user whole process will look like a single application. 

Not mandatory, but might be a good idea to use some kind of simple templating library for formatting the output, so templates can be shared between JVM and Python.

**Comment by bzz** [comment]
As report implementation was included in the release https://github.com/src-d/gemini/releases/tag/v0.0.2 - closing this issue.

Please, feel free to create a new issue for subsequent improvements of the report command!

**Comment by carlosms** [comment]
Here it is: https://github.com/src-d/gemini/issues/110
