### ISSUE TITLE
Query: CPU WMH implementation in Scala 

### ISSUE THREAD

**Issue by bzz** [src-d/gemini#67]
Part of #53 and #55 

For both, query and hashing similar files we need to have a CPU-based [WeightedMinHash](https://blog.sourced.tech/post/minhashcuda/) implementation in JVM, to avoid depending on MinHashCUDA lib and GPU.

Here are few reference implementations of this algorithm:
 - [Go impl](https://github.com/src-d/go-license-detector/blob/d69b5eb70a3f26cb1261ad01fd2f51934f06075a/licensedb/internal/wmh/wmh.go#L64)
 - [Python impl](https://github.com/ekzhu/datasketch/blob/ae9edad7b43ab6eccd86537cc9bfdea11fddb485/datasketch/weighted_minhash.py#L106)
 - [C++ CUDA impl](https://github.com/src-d/minhashcuda/blob/e0aa2758292a4c527a9fea0e25bcd4f4af13b39c/minhashcuda.cc#L564)

It might make sense to research if such library already exists in JVM ecosystem, and if not - it might make sense to implement one in Java as part of Gemini codebase. This way it can be later used from Java, Scala, Clojure, etc eventually, as a standalone library.

Correctness verification is of paramount importance, so we would need to have some tests, and may be a reference data \w hashes of some sets, produced by one of the implementations from above.

**Comment by carlosms** [comment]
Closing, code merged.
