### ISSUE TITLE
Making gemini easier to run

### ISSUE THREAD

**Issue by campoy** [src-d/gemini#84]
After seeing some users face issues running gemini for the first time, I created a new Dockerfile image

See the code here: https://gist.github.com/campoy/d48de3f6aef356e641df36a1fea6a778

Once we have this, running gemini is as easy as:

```bash
docker run -v $(pwd)/siva:/repositories campoy/gemini:quickstart
```

I wonder if this should be part of this repo and where it should be added.

**Comment by smacker** [comment]
with recent improvements we are going to have more external dependencies:
- DB
- Bblfsh server
- Feature extractor service

Putting everything in one Dockerfile might be not the best solution in such case.
I personally use docker-compose for it and it was also proposed by @smola to simplify CI.

Running gemini by one command:
```
docker-compose up
```
looks simple enough for me.

And we even can make it single binary using https://github.com/src-d/go-compose-installer

What do you think?

**Comment by campoy** [comment]
That would work for me too, even depending on minikube would work, since Docker is shipping with it now.

My only concern is currently running gemini requires a bit too much knowledge on the architecture, whatever fixes that I'm ok with.

**Comment by smacker** [comment]
Thanks for pointing at minikube! Actually, @bzz proposed to use it as a way of distribution quite a long time ago.

**Comment by bzz** [comment]
This sounds as a good option for starting bunch of things together. 

@campoy thank you for suggestions, we'll keep it open for now. 

As soon as we finish the file-level similarity implementation covered by a [design doc](https://docs.google.com/document/d/1cInzLuz-qygwrTvddGIbzBnzF4nnsAuk_24a6Nhff0k/edit#) we'll get back to it an improving packaging/running experience.

**Comment by bzz** [comment]
Updated the msg above to include relevant issues. After discussion, decided that #94 is a priority and going to be part of the upcoming release.

If we agree on suggestion of using compose script and `docker run` UX as ones that address the needs - those improvements will be included in subsequent releases.

**Comment by campoy** [comment]
I think it'd be nice to keep in mind too that some people can't run Docker at all.
I know that sounds crazy, but the corporate world is wild.

If we could also have a  document explaining how to run it [the hard way](https://github.com/kelseyhightower/kubernetes-the-hard-way) it'd be very useful to many.

**Comment by bzz** [comment]
Closing this now, due to:
 - there is a simple way of trying it now in https://github.com/src-d/gemini#docker
 - more advanced documentation will be handled in #99  

@campoy please, feel free to re-open if this does not address the issue!
