### ISSUE TITLE
Add URLs to the output of report and query commands

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gemini#9]
Show links to the files when it's found duplicates.

- [x] Add reference hash to DB.
- [x] For Github `https://github.com/<repo>/blob/<ref_hash>/<file_path>`
- [x] For Gitlab - same URL schema is the same as github
- [x] For BitBucket, according to [docs](https://confluence.atlassian.com/bitbucket/hyperlinking-to-source-code-in-bitbucket-824476709.html) ` https://bitbucket.org/<repo>/src/<ref_hash>/<file_path>`

**Comment by marnovo** [comment]
Are the "links" targeting a remote or local address? Could you elaborate a bit? Thanks!

**Comment by dpordomingo** [comment]
The links would point to the GitHub too if the files come from there
`https://github.com/<repo>/blob/HEAD/<file_path>`
If the files come from any other source, it should be analyzed separately

**Comment by bzz** [comment]
Updated issue description \w details on Bitbucket

**Comment by smacker** [comment]
there is also gitlab as I mentioned before. It uses the same url schema as github, but different domain.

**Comment by bzz** [comment]
> there is also gitlab 

BTW, from what I can see https://github.com/src-d/rovers/tree/master/providers there might not be gitlab.com support across the stack yet.

**Comment by smacker** [comment]
but it's possible to run gemini on any repository. It might be gitlab collected by borges without rovers. For us it's 1 line of code, so I think better to add it. Description updated.
