### ISSUE TITLE
Improve docker image management in CI

### ISSUE THREAD

**Issue by carlosms** [src-d/gemini#91]
We have scripts that launch docker images, used by Travis CI. To skip them we look for STYLE_CHECK env var, but that is not the only case we should skip anymore.

`if [[ -z "${STYLE_CHECK}" ]]; then`

From this thread https://github.com/src-d/gemini/pull/83#discussion_r179470639

@carlosms
> Maybe we should find a better way to skip docker images? For instance we will have at some point lint for python, scala, and other possible new tests that need a different env.
> Would it work if in travis.yml we moved the before_script: inside each matrix entry? It would be more verbose, but easier to spot where we are launching docker.
> I'm not sure about the best option, but it's something worth looking into.

@smacker
> current check is copy-past for a script we already use. But I agree is need something better. Maybe also use docker-compose as proposed by smola. 

And from this other thread https://github.com/src-d/gemini/pull/83#discussion_r179478214

@smola 
> I understand this is not strictly related to this PR, since you were already doing this previously with `scripts/start_docker_db.sh`, but you might consider using docker-compose for this in the future.
> 
> It can be easily pre-installed in Travis ([see here](https://docs.travis-ci.com/user/docker/#Using-Docker-Compose)) and it's a single file with more concise syntax to define Docker dependencies. You can choose to start all of them with `up` or specific `up bblfsh`.

@smacker 
> yes. We are going to have 3 docker images (db, bblfsh, feature extraction) in dependencies for gemini. It makes perfect sense to use docker-compose in the feature. (actually, I already do locally)

**Comment by bzz** [comment]
Very nice context and suggestion. 

Will close in favor of more generic #95 that is going to address this improvement
